### ISSUE TITLE
Pod level metrics are not being surfaced by the shim

### ISSUE THREAD

**Issue by kate-goldenring** [spinframework/containerd-shim-spin#180]
This is a summary of a [thread](https://cloud-native.slack.com/archives/C06PC7JA1EE/p1721248525241369) from the #spinkube CNCF slack. Thank you @asteurer for discovering this issue! 

## The issue
Initial discovery: When running a CPU intensive spin app with the shim, if load/ requests increases, CPU usage reporting on the pod stays static (output of `kubectl top pods` does not change). This makes it impossible to use the Horizontal Pod Autoscaler with SpinKube. This is consistent for all of the following tested K8s distributions -- note that the only distribution that does not exhibit this behavior is K3d:

| distro | containerd     |works|
|--------|----------------|-----|
| k3d    | v1.7.7-k3s1.27 | yes |
| AKS    | 1.7.15-1       |  no |
| k3s    | 1.6.28         |  no |
| Kind   | 1.7.15         |  no |

## Repro steps

1. Apply a CPU intensive spin app deployment and the HPA:
 ```yaml
piVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-test
  template:
    metadata:
      labels:
        app: spin-test
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
      - name: spin-test
        image: ghcr.io/spinkube/spin-operator/cpu-load-gen:20240311-163328-g1121986
        command: ["/"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 600M
---
apiVersion: v1
kind: Service
metadata:
  name: spin-test
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: spin-test
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spinapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spin-test
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
```

2. Call the stats API for the node the Pod is running on:
```sh
kubectl get --raw "/api/v1/nodes/$NODE_NAME/proxy/stats/summary?only_cpu_and_memory=true" | grep "spin-test" -C 40
```

Output may look similar to the following:
```sh
  {
   "podRef": {
    "name": "spin-test-66d9dd45f5-csf5j",
    "namespace": "default",
    "uid": "d82c9414-c690-4b0c-925f-4ead983edce4"
   },
   "startTime": "2024-08-21T17:22:33Z",
   "containers": [
    {
     "name": "spin-test",
     "startTime": "2024-08-21T17:22:33Z",
     "cpu": {
      "time": "2024-08-21T17:28:32Z",
      "usageNanoCores": 4728,
      "usageCoreNanoSeconds": 1926321
     },
     "memory": {
      "time": "2024-08-21T17:28:32Z",
      "workingSetBytes": 25096192
     }
    }
   ],
   "cpu": {
    "time": "2024-08-21T17:28:32Z",
    "usageNanoCores": 0,
    "usageCoreNanoSeconds": 0
   },
   "memory": {
    "time": "2024-08-21T17:28:32Z",
    "availableBytes": 599998464,
    "usageBytes": 0,
    "workingSetBytes": 0,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
   }
  },
```
Notice how the Pod CPU and memory usage values are 0 while the container has properly propagated values. 

3. Load the app to see if the HPA increases replicas
If Pod metrics were properly reported, the app replicas would increase.

```sh
# After port forwarding to port 3000
bombardier localhost:3000 -n 10 -t 30s
```

Calling the stats API during the load test shows that while the container `usageNanoCores` jumped from 4728 to 497486, the pod metrics did not change nor did the app replica count or the output of `kubectl top pods` for that Pod.

## Other investigation
Pod metrics are surfaced for normal containers not executed with the shim (without runtime class `wasmtime-spin-v2` specified):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-test
  template:
    metadata:
      labels:
        app: spin-test
    spec:
      containers:
      - name: spin-test
        image: ghcr.io/kate-goldenring/spin-in-container:fib
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spin-test
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: spin-test
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spin-test
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

However, if that same container is executed with the shim, Pod metrics are no longer surfaced. 
```sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test-runwasi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-test-runwasi
  template:
    metadata:
      labels:
        app: spin-test-runwasi
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
      - name: spin-test-runwasi
        image: ghcr.io/kate-goldenring/spin-in-container:fib
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spin-test-runwasi
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: spin-test-runwasi
```

## Possible solutions and areas to investigate
Some areas to investigate that @jsturtevant and @radu-matei mentioned are the following:
- [ ] cgroup version being used
- [ ] how runwasi handles / mocks Pod creation [here](https://github.com/containerd/runwasi/blob/71ae3ee560b30a76a34ac322e0eec27b226d3947/crates/containerd-shim-wasm/src/sandbox/shim/local.rs#L157-L161)
